### ISSUE TITLE
Bitwarden Ticket

### ISSUE THREAD

**Issue by RayBB** [xusoo/tmdb-typescript-api#3]
Hello @xusoo sorry too open a ticket in this very awesome project but I wanted to make sure you're seeing the discussion here: https://github.com/bitwarden/browser/pull/956

Do you think you are willing/able to make the changes to work with safari and remove chrome specific stuff? If not it's totally okay but you should let people know in the thread so someone else can try to pick it up :)

**Comment by xusoo** [comment]
I posted a possible solution yesterday 😄 Today I will update the PR 👍
